import fs from "node:fs";
import path from "node:path";
import { which, run, stateDir, readJson, humanDuration, resolveBin } from "./util.mjs";
import { loadConfig } from "./config.mjs";
import { installedModels, installedModelsSmart, openrouterCatalog, modelsDevCatalog, budgetCheck, spentToday } from "./models.mjs";
import { listJobIds, readJob, refreshAll } from "./jobs.mjs";

export async function doctor({ repo = process.cwd(), warmup = false } = {}) {
  const cfg = loadConfig(repo);
  const out = { ok: true, problems: [], warnings: [], info: {} };
  const fail = (m, fix) => { out.ok = false; out.problems.push(fix ? `${m} → ${fix}` : m); };
  const warn = (m) => out.warnings.push(m);

  // 1. binaries
  const bin = which(cfg.opencodeBin);
  out.info.opencode = bin ?? "NOT FOUND";
  if (bin && !cfg.opencodeBin.includes("/")) out.info.opencodeResolved = bin;
  if (!bin) fail(`opencode binary "${cfg.opencodeBin}" not found`, "npm i -g opencode-ai");
  else {
    // Existing is not the same as runnable: on Windows npm also writes an
    // extension-less shell shim that node cannot start at all.
    const v = await run(bin, ["--version"], { timeout: 20000 });
    const version = (v.stdout || "").trim();
    out.info.opencodeVersion = version || "NOT RUNNABLE";
    if (!version) {
      fail(`found ${bin} but could not run it (${(v.stderr || v.error || "no output").toString().trim().slice(0, 200)})`,
        process.platform === "win32"
          ? "that is usually npm's extension-less shim; re-run `node bin\\ocfleet.mjs install` to pin the real .exe"
          : "check the path in fleet.config.json (opencodeBin)");
    }
  }
  const gitPath = (await import("./util.mjs")).gitBin(cfg);
  const gitOk = gitPath && gitPath !== "git" ? which(gitPath) : which("git");
  out.info.git = gitOk ?? "NOT FOUND";
  if (!gitOk) fail("git not found", process.platform === "win32"
    ? "install Git for Windows (https://git-scm.com/download/win) — worktree isolation needs it"
    : "install git — worktree isolation needs it");
  if (gitOk) {
    const gv = await run(gitOk, ["--version"], { timeout: 15000 });
    if (!gv.stdout?.trim()) {
      fail(`found ${gitOk} but could not run it`, "check gitBin in fleet.config.json");
    }
  }
  out.info.node = process.version;
  out.info.platform = `${process.platform}/${process.arch}`;
  if (Number(process.versions.node.split(".")[0]) < 18) {
    fail(`node ${process.version} is too old`, "install node 18 or newer");
  }
  if (process.platform === "win32") {
    out.info.windowsNote =
      "opencode itself recommends WSL on Windows for full compatibility; native runs work but are less tested. " +
      "If jobs behave oddly, try the same setup inside WSL before debugging the fleet.";
  }

  // 2. config
  out.info.configSources = cfg._sources?.length ? cfg._sources : ["built-in defaults only"];
  out.info.stateDir = stateDir();
  // The settings people actually wonder about mid-run. Without this, "why are only
  // four workers running?" has no visible answer — the number lives in a config file
  // that overrides the built-in default silently.
  // Say how old the candidate lists are: a stale profile breaks nothing, which is
  // exactly why nobody notices it until the models in it are a year out of date.
  if (cfg.profilesWrittenAt) {
    const days = Math.floor((Date.now() - Date.parse(cfg.profilesWrittenAt)) / 86400e3);
    const max = cfg.defaults?.profileMaxAgeDays ?? 7;
    out.info.profilesAge = `${days}d old` + (max > 0
      ? (days >= max ? ` — re-ranked on the next delegation` : `, refreshed after ${max}d`)
      : ` — auto-refresh disabled (profileMaxAgeDays: 0)`);
  } else {
    out.info.profilesAge = "not generated by `suggest` — hand-written or built-in, so they are never auto-refreshed. Run `ocfleet suggest --write` once to hand them over.";
  }
  out.info.defaults = {
    profile: cfg.defaults.profile,
    maxConcurrentJobs: cfg.defaults.maxConcurrentJobs,
    timeoutSec: cfg.defaults.timeoutSec,
    worktree: cfg.defaults.worktree,
    failover: cfg.defaults.failover,
    maxAttempts: cfg.defaults.maxAttempts
  };
  out.info.budget = cfg.budget;

  // 3. models
  let installed = [];
  if (bin) {
    installed = await installedModelsSmart(cfg, { bin, cwd: repo, refresh: true });
    out.info.installedModelCount = installed.length;
    if (!installed.length) fail("opencode reports no models", "run: opencode auth login (pick openrouter / zai / deepseek)");
  }
  const cat = await import("./catalog.mjs");
  const authProviders = cat.authenticatedProviders({ repo });
  const authFiles = cat.authSources();
  out.info.authenticatedProviders = authProviders.length ? authProviders : "none detected";
  if (authFiles.length) out.info.credentialsFrom = authFiles;
  if (!authProviders.length) {
    // Not finding the file is not proof that nobody is logged in — the location
    // differs per platform. Say which is the case instead of crying wolf.
    if ((out.info.installedModelCount ?? 0) > 20) {
      warn("could not locate opencode's credential file, so model suggestions are not filtered by provider. " +
           "opencode itself reports models, so you are probably signed in — check with `opencode auth list`.");
    } else {
      warn("no provider credentials found — every delegation will fail until you run `opencode auth login`");
    }
  }

  let orCatalog = {}, mdCatalog = {};
  try { orCatalog = await openrouterCatalog(); out.info.openrouterCatalogue = Object.keys(orCatalog).length + " models"; }
  catch (e) { warn(`OpenRouter price catalogue unavailable: ${e.message} — prices for openrouter/* cannot be checked`); }
  try {
    mdCatalog = await modelsDevCatalog();
    out.info.modelsDevCatalogue = `${Object.keys(mdCatalog).length} providers`;
  } catch (e) { warn(`models.dev catalogue unavailable: ${e.message} — non-OpenRouter models will look unpriced`); }
  if (!Object.keys(mdCatalog).length) warn("models.dev catalogue empty — providers other than OpenRouter cannot be priced");

  const known = new Set(installed);
  out.info.profiles = {};
  for (const [name, prof] of Object.entries(cfg.profiles ?? {})) {
    const rows = (prof.candidates ?? []).map((c) => {
      const present = known.has(c);
      const chk = budgetCheck(c, cfg, orCatalog, { mdCatalog });
      return { model: c, available: present, allowed: chk.allowed, reason: present ? (chk.allowed ? "ok" : chk.reason) : "provider not configured" };
    });
    const usable = rows.find((r) => r.available && r.allowed);
    out.info.profiles[name] = { usable: usable?.model ?? null, candidates: rows };
    // only nag about profiles you would actually hit
    if (!usable && (name === cfg.defaults.profile || ["cheap", "balanced", "strong"].includes(name))) {
      warn(`profile "${name}" has no usable model — configure a provider or run \`ocfleet suggest --write\``);
    }
  }
  if (!Object.values(out.info.profiles).some((p) => p.usable)) {
    fail("no profile can route anywhere", "opencode auth login, then `ocfleet models` to see what is allowed");
  }

  // 4. spend
  const spend = spentToday();
  out.info.spentTodayUsd = Number((spend.total ?? 0).toFixed(4));
  out.info.dailyLimitUsd = cfg.budget.maxDailyUsd;
  if (cfg.budget.maxDailyUsd && spend.total >= cfg.budget.maxDailyUsd) fail("daily budget exhausted", "raise budget.maxDailyUsd or wait for tomorrow");

  // 5. jobs
  const jobs = await refreshAll();
  const running = jobs.filter((j) => j.state === "running");
  const queued = jobs.filter((j) => j.state === "queued");
  out.info.jobs = { total: jobs.length, running: running.length, queued: queued.length,
    stale: running.filter((j) => Date.now() - j.startedMs > (j.timeoutSec + 120) * 1000).map((j) => j.id) };
  if (queued.length) {
    out.info.jobs.note = `${queued.length} waiting for one of ${cfg.defaults.maxConcurrentJobs} worker slots`
      + (cfg._sources?.length ? ` (defaults.maxConcurrentJobs in ${cfg._sources[cfg._sources.length - 1]})` : "");
  }
  if (out.info.jobs.stale.length) warn(`stale jobs past their timeout: ${out.info.jobs.stale.join(", ")} — fleet_cancel them`);

  // 6. warm up provider packages (first real run downloads npm packages and can look like a hang)
  if (warmup && bin) {
    const model = out.info.profiles[cfg.defaults.profile]?.usable
      ?? Object.values(out.info.profiles).map((p) => p.usable).find(Boolean);
    if (model) {
      const t0 = Date.now();
      // --print-logs so a failure says *why*; the first run of a new provider
      // downloads its npm package and can legitimately take minutes.
      const r = await run(bin,
        ["run", "--print-logs", "--log-level", "INFO", "--model", model, "reply with the single word: ready"],
        { timeout: 600000, cwd: repo });
      const tail = (r.stderr || "").trim().split("\n").slice(-6).join("\n");
      out.info.warmup = {
        model, duration: humanDuration(Date.now() - t0), ok: r.ok,
        output: (r.stdout || "").trim().slice(-200) || undefined,
        lastLogLines: r.ok ? undefined : tail || "(no output — opencode hung before logging)"
      };
      if (!r.ok) {
        warn(`warmup with ${model} did not finish. If the log ends at package resolution it was just slow — run doctor --warmup again. ` +
             `A 401/402 means the provider key or credit is the problem.`);
      }
    } else out.info.warmup = "skipped, no usable model";
  }

  if (out.ok && !out.warnings.length) out.summary = "fleet ready";
  else out.summary = `${out.problems.length} problem(s), ${out.warnings.length} warning(s)`;
  return out;
}
